name: Merge on master
on:
  push:
    branches:
      - master

jobs:
  release-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ftrip-io/github-ci/semantic-release@ec6edefa23f5cc46ef0d464981e7d36e5d9ea31a
        id: semantic-release
        with:
          install-changelog: "true"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ftrip-io/github-ci/build-and-push-to-dockerhub@ef2fd6ac85fe9e0ae63e5979a82a35bd5075bc33
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          context: "."
          tags: ftripio/image-service:latest, ftripio/image-service:${{ steps.semantic-release.outputs.next-version }}
